### ISSUE TITLE
mqtt-to-rf?

### ISSUE THREAD

**Issue by Omirax** [matfra/rf2mqtt#1]
Perfect work!

What about mqtt-to-rf? 
It's possible?

Best Regards,

**Comment by matfra** [comment]
Yes, for this I use the native rpi_rf support in home assistant:
```
switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      tripod:
        code_on: 5330691
        code_off: 5330700
        pulselength: 176
        protocol: 1
      lamp:
        code_on: 5330227
        code_off: 5330236
        pulselength: 176
        protocol: 1
```
